import { Shield, Lock, Database, Eye } from "lucide-react";

const sections = [
  {
    icon: Database,
    title: "Data Collection",
    content: [
      "EvEr SmArT KnOwLeDgE hUb does not collect, transmit, or store any personal data on external servers.",
      "All data generated by the app — notes, reading history, preferences — remains exclusively on your device.",
      "We do not use analytics services, crash reporting tools, or any third-party SDKs that phone home.",
    ],
  },
  {
    icon: Lock,
    title: "Local Storage",
    content: [
      "All app data is stored in your device's local storage or file system.",
      "You have full control over your data and can delete it at any time by clearing the app's data or uninstalling.",
      "No backup services or cloud synchronization are performed without your explicit action.",
    ],
  },
  {
    icon: Eye,
    title: "Permissions",
    content: [
      "The app may request storage permissions to read and write local files for the Reader Workspace feature.",
      "No network, location, contacts, camera, or microphone permissions are requested or required.",
      "All requested permissions are strictly necessary for the stated features and nothing more.",
    ],
  },
  {
    icon: Shield,
    title: "Third-Party Services",
    content: [
      "The app does not integrate any third-party advertising networks.",
      "No social media SDKs or tracking pixels are embedded in the application.",
      "Book content sourced in the Books Store is obtained from official and publicly available sources.",
    ],
  },
];

export default function Privacy() {
  return (
    <div className="pt-24 pb-16">
      <div className="container mx-auto px-4 lg:px-8 max-w-4xl">
        {/* Header */}
        <div className="text-center mb-16">
          <span className="inline-block px-3 py-1 rounded-full bg-accent text-accent-foreground text-xs font-semibold mb-4 uppercase tracking-wider">
            Legal
          </span>
          <h1 className="font-display font-bold text-4xl sm:text-5xl mb-4">
            Privacy{" "}
            <span className="gradient-text">Policy</span>
          </h1>
          <p className="text-muted-foreground text-base">
            Last updated: June 2026
          </p>
          <p className="text-muted-foreground mt-4 text-lg max-w-xl mx-auto">
            Your privacy is not just a policy for us — it is the foundation of everything we build.
          </p>
        </div>

        {/* Intro */}
        <div className="bg-accent rounded-2xl p-6 mb-10 border border-primary/20">
          <p className="text-accent-foreground font-medium text-sm leading-relaxed">
            <strong>Short version:</strong> EvEr SmArT KnOwLeDgE hUb is 100% offline. We collect
            zero personal data. Everything stays on your device. There are no ads, no tracking, and
            no subscriptions that require your personal information.
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-6">
          {sections.map((section) => {
            const Icon = section.icon;
            return (
              <div
                key={section.title}
                className="bg-card border border-border rounded-2xl p-8"
              >
                <div className="flex items-center gap-3 mb-5">
                  <div className="w-10 h-10 rounded-xl gradient-brand flex items-center justify-center shadow-md">
                    <Icon size={18} className="text-white" />
                  </div>
                  <h2 className="font-display font-semibold text-xl">{section.title}</h2>
                </div>
                <ul className="space-y-3">
                  {section.content.map((item, i) => (
                    <li key={i} className="flex items-start gap-3 text-muted-foreground text-sm leading-relaxed">
                      <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary/60 flex-shrink-0" />
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            );
          })}
        </div>

        {/* Contact */}
        <div className="mt-12 bg-card border border-border rounded-2xl p-8 text-center">
          <h3 className="font-display font-semibold text-xl mb-3">Questions?</h3>
          <p className="text-muted-foreground text-sm leading-relaxed max-w-md mx-auto">
            If you have any questions about this Privacy Policy or how EvEr SmArT KnOwLeDgE hUb
            handles your data, please reach out through our open source community channels.
          </p>
        </div>
      </div>
    </div>
  );
}
